import Head from "next/head";
import Wave1 from "@/components/Wave1";
import Wave2 from "@/components/Wave2";
import Wave3 from "@/components/Wave3";
import Header from "@/components/Header";
import Presentation from "@/components/Presentation";
import AboutText from "@/components/AboutSection";
import TechnologiesSection from "@/components/TechnologiesSection";
import ProjectsSection from "@/components/ProjectsSection";
import Footer from "@/components/Footer";
import BackToTopButton from "@/components/BackToTopButton";
import LazyLoad from "react-lazyload";
export default function Home() {
  return (
    <main>
      <Head>
        <title> Pedro Rassier | Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/progIco.ico" />
      </Head>
      <Header />
      <Presentation />
      <Wave1 />
      <AboutText />
      <LazyLoad offset={100}>
        <Wave2 />
        <TechnologiesSection />
      </LazyLoad>
      <Wave3 />
      <ProjectsSection />
      <Footer />
      <BackToTopButton />
    </main>
  );
}
